import Nav from "@/components/marketing/Nav";
import Footer from "@/components/marketing/Footer";
import { getSession } from "@/lib/session";

export const metadata = { title: "Terms of Service — Nookly" };

export default async function TermsPage() {
  const session = await getSession();

  return (
    <div className="flex flex-1 flex-col bg-white">
      <Nav isAuthenticated={Boolean(session)} />
      <main className="mx-auto w-full max-w-3xl flex-1 px-6 py-16">
        <h1 className="text-3xl font-bold text-zinc-900">Terms of Service</h1>
        <p className="mt-2 text-sm text-zinc-500">Last updated: {new Date().toLocaleDateString("en-PH", { year: "numeric", month: "long", day: "numeric" })}</p>

        <div className="prose prose-zinc mt-8 max-w-none space-y-6 text-sm leading-relaxed text-zinc-700">
          <section>
            <h2 className="text-lg font-semibold text-zinc-900">1. Your workspace</h2>
            <p>
              Nookly provides point-of-sale, inventory, and reporting software as a service to drugstores and
              pharmacies (&quot;you,&quot; &quot;your workspace&quot;) on a subscription basis. When you sign up, we
              create an isolated workspace for your business. You&apos;re responsible for the accuracy of the
              business, staff, and product information you enter, and for keeping your login credentials
              confidential.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-zinc-900">2. Plans, trials, and billing</h2>
            <p>
              New workspaces start on a 14-day free trial. No payment is collected automatically — to change plans,
              you submit a request in-app and our team will contact you to arrange payment before the new plan is
              activated. We may suspend a workspace for non-payment after reasonable notice.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-zinc-900">3. Not a BIR-accredited system</h2>
            <p>
              Nookly is not currently accredited by the Bureau of Internal Revenue. Receipts generated by Nookly are
              labeled as Acknowledgement Receipts and are not Official Receipts or Sales Invoices for tax purposes.
              You remain solely responsible for your own tax compliance and for using accredited invoicing where
              required by law.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-zinc-900">4. Acceptable use</h2>
            <p>
              You agree not to use Nookly for unlawful purposes, to attempt to access another workspace&apos;s data,
              or to interfere with the platform&apos;s normal operation. We may suspend accounts that violate this.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-zinc-900">5. Data and your customers&apos; data</h2>
            <p>
              You&apos;re responsible for having a lawful basis to store your customers&apos; and staff&apos;s personal
              and health-related information (e.g. prescription records) in Nookly, consistent with the Philippine
              Data Privacy Act of 2012. See our <a href="/privacy" className="text-emerald-700 underline">Privacy Policy</a>{" "}
              for how we handle data on your behalf.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-zinc-900">6. Cancellation</h2>
            <p>
              You may stop using Nookly at any time. Contact us to request export or deletion of your workspace
              data.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-zinc-900">7. Changes</h2>
            <p>
              We may update these terms from time to time. Continued use of Nookly after an update constitutes
              acceptance of the revised terms.
            </p>
          </section>

          <p className="text-xs text-zinc-400">
            Questions about these terms? Reach out through the in-app support ticket system or your account
            contact.
          </p>
        </div>
      </main>
      <Footer />
    </div>
  );
}
